### ISSUE TITLE
Training with custom dataset

### ISSUE THREAD

**Issue by chrischen0606** [dominickrei/pi-vit#3]
Thank you for the excellent work utilizing 2D and 3D pose for action recognition! I have a few questions I would appreciate your insights on:

1. Is it possible to modify the code to customize the actions being recognized?
2. If I have my own dataset with 2D and 3D poses (aligned to the pelvis), would that be sufficient to build a customized Pi-vit model?

Looking forward to your response at your earliest convenience!

**Comment by dominickrei** [comment]
Hi @chrischen0606, Thanks for your interest! Both of the changes you mentioned are possible with pi-vit.

1. You would need to change [this line](https://github.com/dominickrei/pi-vit/blob/main/configs/Smarthome/PIViT_Smarthome.yaml#L54) in the config file to match the number of classes in your dataset. You would also need to build a CSV following the format [here](https://github.com/dominickrei/pi-vit/tree/main?tab=readme-ov-file#preparing-csvs)
2. This is possible but it is a bit more involved
    * For 2D-SIM the quickest solution is to format your poses to the same format as Toyota Smarthome, you can download the dataset to find the format of their poses. [This part of the code](https://github.com/dominickrei/pi-vit/blob/main/timesformer/datasets/smarthome.py#L286) might be helpful to look at as well
    * For 3D-SIM you will need to train Hyperformer using your 3D pose data, extract the features from the Hyperformer model, and save them in the h5py format we use in the code. [This part of the code](https://github.com/dominickrei/pi-vit/blob/main/timesformer/models/losses.py#L61) might be helpful

I hope this helps! Let me know if you have other questions.

**Comment by chrischen0606** [comment]
Appreciate for the response!
